### PR TITLE
Implement CO2KenNFTCollection and CO2KenNFTERC20

### PR DESCRIPTION
**Pull request by leolara**

### CODE REVIEW

**Comment by marceljay** [comment]
MetaData / struct attributes:

Have a look [at these CVCUs batch mint jsons.](https://github.com/creol-io/cvcu/blob/main/batches/batch1.json)

I would say the struct should contain the following fields (for now), in a minimal version:

- string projectName
- string symbol (ticker... which format? maybe best set automatically, e.g. GS-US-18)
- string/uint vintage (could there be chars or months in the vintage?)
- string standard
- string registry
- string serialnumber   (string because format could contain chars?)
- string countryCode (full country name in meta data?)
- uint quantity (or CO2tons) 


Are all of these necessary? What do you think @jamespfarrell

**Comment by jamespfarrell** [comment]
I think this diagram is probably good in terms of what data we need 
image

**Comment by jamespfarrell** [comment]
@leolara Could you please remove the ERC20 contract code, so that we can merge this?

**Comment by leolara** [comment]
I don't think we should merge this after our conversation. I don't think the vintage will be a NFT. Will write later

**Comment by marceljay** [comment]
@leolara What is the we want to go? :) 
The current architectural design was made by Rapha and I and I wrote my  code according to that design.
Regarding tests: I've never written tests, happy to have your support here.

**Comment by marceljay** [comment]
I also would say tests are of secondary importance for now, we want to validate our design with experienced solidity devs, not sure if tests are necessary to do that. But please let me know you think writing the tests later would be a huge mistake.

**Comment by leolara** [comment]
I cannot go into this today. I will check on the weekend

**Comment by leolara** [comment]
Anyway this code make NFTs of project-vinatages, and for the architecture you have it should be for actual batches of serial numbers. I do not see the rush of merging things that are wrong

**Comment by marceljay** [comment]
We want to ship code of a v0.1 MVP to be reviewed by some DeFi OGs and Kernel Mentors. Expo week is next week and I think it would be cool if we can show some code, if there is interest. Hence the "rush". I'd say you can come up with a better design and we can build that afterwards.

**Comment by leolara** [comment]
Ok, so then we should focus on cleaning the code, I am getting mixed signals about what is the goal, a demo, showing the code to someone, developing an architecture for the final demo at the end of Kernel.

I will try to get this more similar to your architecture on the weekend

**Comment by marceljay** [comment]
cool! I think we do not know what the goal is regarding the mid-Expo on Tuesday, we should focus on output, and it does not have to perfect. We will re-iterate over it until the final Expo.

**Pull request merged**
